use W3Resource
go 

--Lesson SQL-4 Task 4

--Question 1. From the following table, write a SQL query to select all the salespeople.
--Return salesman_id, name, city, commission with the percent sign (%).

Select salesman_id, name, city, '%' as percentage, commission * 100 as commission from Inventory.Salesman

--Question 2. From the following table, write a SQL query to find the number of orders booked for each day.
--Return the result in a format like "For 2001-10-10 there are 15 orders".". 

Select 'For' as Col1, ord_date, ',There are', count(ord_no) as OrderCount, 'orders.' as Orders from Inventory.Orders
group by ord_date;

--Qeustion 3. From the following table, write a SQL query to find all the orders.
--Sort the result-set in ascending order by ord_no. Return all fields. 

Select * from Inventory.Orders
order by ord_no; 

--Question From the following table, write a SQL query to find all the orders.
--Sort the result-set in descending order by ord_date. Return all fields. 

Select * from Inventory.Orders
order by ord_date desc;

--Question From the following table, write a SQL query to find all the orders.
--Sort the result-set in descending order by ord_date and purch_amt. Return all fields.  

Select * from Inventory.Orders
order by ord_date desc, purch_amt desc;

--Question From the following table, write a SQL query to find all the customers. Sort the result-set by customer_id.
--Return cust_name, city, grade.

Select cust_name, city, grade from Inventory.Customer
order by customer_id;

--Question 7. From the following table, write a SQL query that calculates the maximum purchase amount
--generated by each salesperson for each order date.
--Sort the result-set by salesperson id and order date in ascending order.
--Return salesperson id, order date and maximum purchase amount. 

Select salesman_id, ord_date, max(purch_amt) as MaxAmount from Inventory.Orders 
group by salesman_id, ord_date
order by salesman_id asc, ord_date asc;

--Question 8. From the following table, write a SQL query to find all the customers. 
--Sort the result-set in descending order on 3rd field.
--Return customer name, city and grade. 

Select cust_name, city, grade from Inventory.Customer
order by 3 desc;

--Question 9. From the following table, write a SQL query that counts the unique orders
--and the highest purchase amount for each customer. Sort the result-set in descending order on 2nd field.
--Return customer ID, number of distinct orders and highest purchase amount by each customer. 

Select customer_id, count(distinct ord_no) as DistinctOrder, max(purch_amt) from Inventory.Orders
group by customer_id
order by 2 desc; 

--Question 10. From the following table, write a SQL query to calculate the summation of purchase amount, 
--total commission (15% for all salespeople) by each order date. Sort the result-set on order date.
--Return order date, summation of purchase amount and commission.

Select ord_date, sum(purch_amt) as TotalPurchase, sum(purch_amt)/100*15 as '15%' from Inventory.Orders
group by ord_date
order by ord_date;





